=== miguel2694/Practica-xsd-2/extensiones/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ciudades">
    <xs:complexType>
            <xs:sequence>
              <xs:element name="ciudad" type="xs:string"/>
              <xs:element name="fecha-de-nacimiento" type="xs:date"/>
              <xs:element name="hora"/>
                <xs:element name ="nota" type="xs:float"/>
                <xs:element name="apto" type= "xs:boolean"/>
                <xs:element name="puertaCerrada" type="xs:boolean"/>
                <xs:element name="puertaAbierta" type="xs:boolean"/>
                </xs:sequence>
                </xs:complexType>
            </xs:element>     
</xs:schema>

=== miguel2694/Practica-xsd-2/extensiones/ciudad.xml
<?xmlns version="1.0" encoding="UTF-8" ?>
<ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ciudad.xsd">

<ciudad >Roma </ciudad>
    <fecha-de-nacimiento>1996-12-18 </fecha-de-nacimiento >
    <hora>18:29:45</hora>
    <nota>7.5 </nota >
    <apto>true </apto>
    <puertaCerrada>true</puertaCerrada>
    <puertaAbierta>false</puertaAbierta>
</ciudades>
